cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove, name='cart_remove'),
]

coupns/urls.py
from django.urls import path
from . import views

app_name = 'coupns'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
]

shop/urls.py
from django.urls import path
from . import views
app_name = 'shop'
urlpatterns = [
    path('',views.product_list,name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    
]

xeroshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
app_name='shop'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupns/', include('coupns.urls', namespace='coupns')),
    path('',include('shop.urls', namespace="shop")),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('newsletter/',include('newsletters.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from coupns.forms import CouponApplyForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
            item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],'update': True})

    coupon_apply_form = CouponApplyForm()
    return render(request, 'cart/detail.html', {'cart': cart, 'coupon_apply_form': coupon_apply_form})

cart/templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  Your shopping cart
{% endblock %}

{% block content %}


<table class="table">
  <thead class="bg-info">
    <tr>
      <th scope="col">Image</th>
      <th scope="col">Product</th>
      <th scope="col">Qyantity</th>
      <th scope="col">Remove</th>
      <th scope="col">Unit Price</th>
      <th scope="col">Price</th>
    </tr>
  </thead>
  <tbody class="table-secondary">
  {% for item in cart %}
        {% with product=item.product %}
    <tr>
      <th>
        <a href="{{ product.get_absolute_url }}">
          <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" style="height: 150px; width: 250px;">
        </a>
      </th>
      <td>{{ product.name }}</td>
      <td>
        <form action="{% url 'cart:cart_add' product.id %}" method="post">
            {% csrf_token %}
            {{ item.update_quantity_form.quantity }}
            {{ item.update_quantity_form.update }}
            <button type="submit" class="btn btn-info">Update</button>
        </form>
      </td>
      <td><a href="{% url 'cart:cart_remove' product.id %}" class="nav-link active">Remove</a>
      </td>
      <td>${{ item.price }}</td>
      <td>${{ item.total_price }}</td>
       {% endwith %}
  {% endfor %}
    </tr>
  {% if cart.coupon %}
  <tr class="bg-primary">
    <td>Sub Total</td>
        <td colspan="4"></td>
        <td data-th="Subtotal" class="text-center">${{ cart.get_total_price|floatformat:"2" }}</td>
  </tr>
  <tr class="bg-disable">
    <td>"{{ cart.coupon.code }}" coupon ({{ cart.coupon.discount }}% off)</td>
        <td colspan="4"></td>
        <td data-th="Subtotal" class="text-center">
             - ${{ cart.get_discount|floatformat:"2" }}
        </td>
  </tr>
  {% endif %}
  <tr class="bg-danger">
    <td>Total</td>
        <td colspan="4"></td>
        <td data-th="Subtotal" class="text-center">
            ${{ cart.get_total_price_after_discount|floatformat:"2" }}
        </td>
  </tr>
  </tbody>

</table>
  <!--
        <form class="card" action="{% url 'coupns:apply' %}" method="post">{% csrf_token %}
            <div class="input-group">
              <div class="input-group-append">
                  {{ coupon_apply_form }}
                <button type="submit" class="btn btn-secondary">Redeem</button>
              </div>
            </div>
          </form>
-->
    <p>Apply a Coupon: </p>
    <form action="{% url 'coupns:apply' %}" method="post">{% csrf_token %}
        <div class="input-group">
              <div class="input-group-append">
                  {{ coupon_apply_form}}
              </div>
        </div>
        <button class="btn btn-primary" type="submit">Apply</button>
    </form>

<p class="text-right">
    <a href="{% url 'shop:product_list' %}">
      <button type="button" class="btn btn-outline-secondary">Continue shopping</button>
    </a>
  <a href="{% url 'orders:order_create' %}">
    <button type="button" class="btn btn-info">Checkout</button>
  </a>
  </p>


<!--
  <h1>Your shopping cart</h1>
  <table id="cart" class="table table-hover table-condensed">
    <thead>
      <tr>
        <th style="width:50%">Image</th>
        <th style="width:10%">Product</th>
        <th style="width:10%">Quantity</th>
        <th style="width:10%">Remove</th>
        <th style="width:10%">Unit price</th>
        <th style="width:10%">Price</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td data-th="Product">
              <div class="row">
                <div class="col-sm-2 hidden-xs">
              <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
              </a>
                </div>
                <div class="col-sm-10">
                  <p>{{ product.name }}</p>
                </div>
              </div>
            </td>
            <td>{{ product.name }}</td>
            <td data-th="Quantity">
              <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {% csrf_token %}
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                <input type="submit" value="Update">
              </form>
            </td>
            <td><a href="{% url 'cart:cart_remove' product.id %}">Remove</a></td>
            <td data-th="Price">${{ item.price }}</td>
            <td data-th="Subtotal" class="text-center">${{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr class="total">
        <td>Total</td>
        <td colspan="4"></td>
        <td data-th="Subtotal" class="text-center">${{ cart.get_total_price }}</td>
      </tr>
    </tbody>
  </table>
  <p class="text-right">
    <a href="" class="button light">Continue shopping</a>

    <a href="" class="button">
      Checkout
    </a>
  </p>
-->
{% endblock %}


<!--https://bootsnipp.com/snippets/W0GDr -->