cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove, name='cart_remove'),
]

shop/urls.py
from django.urls import path
from . import views
app_name = 'shop'
urlpatterns = [
    path('',views.product_list,name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    
]

xeroshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
app_name='shop'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupns/', include('coupns.urls', namespace='coupns')),
    path('',include('shop.urls', namespace="shop")),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('newsletter/',include('newsletters.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
            return reverse('shop:product_list_by_category',
                           args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
            return reverse('shop:product_detail', args=[self.id, self.slug])

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from django.db.models import Q
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from cart.forms import CartAddProductForm


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    search = request.GET.get('q')
    if search:
        products = products.filter(
            Q(name__icontains=search) |
            Q(slug__icontains=search)
        )
    paginator = Paginator(products, 8)
    page = request.GET.get('page')
    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        items = paginator.page(paginator.num_pages)
    index = items.number - 1
    max_index = len(paginator.page_range)
    start_index = index - 2 if index >= 2 else 0
    end_index = index + 2 if index <= max_index else max_index
    page_range = paginator.page_range[start_index:end_index]
    context = {
        'category': category,
        'categories': categories,
        'products': products,
        'items': items,
        'page_range': page_range,
    }
    return render(request,'index.html',context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product, pk=id, slug=slug,available=True)
    cart_product_form = CartAddProductForm()
    related = Product.objects.filter(category=product.category).exclude(id=id)[:4]
    return render(request,'detail.html',{'product': product, 'related':related, 'cart_product_form': cart_product_form})




#REST FRAMEWORK TUTORIAL
#https://www.andreagrandi.it/2016/09/28/creating-production-ready-api-python-django-rest-framework-part-1/

shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %} Homepage {% endblock %} </title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/shop-homepage.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/iconic/css/material-design-iconic-font.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/linearicons-v1.0.0/icon-font.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
    <!--
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/demo.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style_common.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style10.css' %}" />
    -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/1.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css' />
    <!-- Leroy Zoom -------->
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.leroy-zoom.min.css' %}">

    {% block stylesheet %}

    {% endblock %}
  </head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="{% url 'shop:product_list' %}">xeroshop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'shop:product_list' %}">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Services</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Contact</a>
            </li>
          </ul>
              <a href="{% url 'cart:cart_detail' %}">
                <button class="btn btn-success btn-lg">
                {% with total_items=cart|length %}
                  {% if cart|length > 0 %}
                  <span class="fa fa-shopping-cart"></span>
                  <span class="items">{{ total_items }}</span>
                  {% else %}
                     <span class="fa fa-shopping-cart"><span class="items"></span></span>
                  {% endif %}
                {% endwith %}
                </button>
              </a>
          <form class="form-inline my-2 my-lg-0" action="" method="GET">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q" value="{{ request.GET.q }}">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
    <div class="container">
      {% block content %}

      {% endblock %}
    </div>
    <!-- footer -->
    <footer class="bg3 p-t-75 p-b-32">
		<div class="container">
			<div class="row">
				<div class="col-sm-6 col-lg-3 p-b-50">
					<h4 class="stext-301 cl0 p-b-30">
						Categories
					</h4>

					<ul>
                        {% for c in categories %}
						<li class="p-b-10">
							<a href="{{ c.get_absolute_url }}" class="stext-107 cl7 hov-cl1 trans-04">
								{{ c.name }}
							</a>
						</li>
                        {% endfor %}
					</ul>
				</div>

				<div class="col-sm-6 col-lg-3 p-b-50">
					<h4 class="stext-301 cl0 p-b-30">
						Help
					</h4>

					<ul>
						<li class="p-b-10">
							<a href="#" class="stext-107 cl7 hov-cl1 trans-04">
								Track Order
							</a>
						</li>

						<li class="p-b-10">
							<a href="#" class="stext-107 cl7 hov-cl1 trans-04">
								Returns
							</a>
						</li>

						<li class="p-b-10">
							<a href="#" class="stext-107 cl7 hov-cl1 trans-04">
								Shipping
							</a>
						</li>

						<li class="p-b-10">
							<a href="#" class="stext-107 cl7 hov-cl1 trans-04">
								FAQs
							</a>
						</li>
					</ul>
				</div>

				<div class="col-sm-6 col-lg-3 p-b-50">
					<h4 class="stext-301 cl0 p-b-30">
						GET IN TOUCH
					</h4>

					<p class="stext-107 cl7 size-201">
						Any questions? Let us know in store at 8th floor, 379 Hudson St, New York, NY 10018 or call us on (+1) 96 716 6879
					</p>

					<div class="p-t-27">
						<a href="#" class="fs-18 cl7 hov-cl1 trans-04 m-r-16">
							<i class="fa fa-facebook"></i>
						</a>

						<a href="#" class="fs-18 cl7 hov-cl1 trans-04 m-r-16">
							<i class="fa fa-instagram"></i>
						</a>

						<a href="#" class="fs-18 cl7 hov-cl1 trans-04 m-r-16">
							<i class="fa fa-pinterest-p"></i>
						</a>
					</div>
				</div>

				<div class="col-sm-6 col-lg-3 p-b-50">
					<h4 class="stext-301 cl0 p-b-30">
						Newsletter
					</h4>

					<form method="post" action="{% url 'subscribe' %}"> {% csrf_token %}
						<div class="wrap-input1 w-full p-b-4">
							<input class="input1 bg-none plh1 stext-107 cl7" type="text" name="email" placeholder="email@example.com">
							<div class="focus-input1 trans-04"></div>
						</div>

						<div class="p-t-18">
							<button class="flex-c-m stext-101 cl0 size-103 bg1 bor1 hov-btn2 p-lr-15 trans-04">
								Subscribe
							</button>
						</div>
					</form>
				</div>
			</div>

			<div class="p-t-40">
				<p class="stext-106 cl6 txt-center">
                Copyright &copy;<script>document.write(new Date().getFullYear());</script> xeroshop || All rights reserved.
				</p>
			</div>
		</div>
	</footer>
    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendor/jquery/jquery-latest.min.js' %}" type="text/javascript"></script>
    <script type="text/javascript" src="{% static 'js/jquery.leroy-zoom.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

<script type="text/javascript">
$(document).ready(function() {
        $("#demo-trigger").leroyZoom({
            zoomTop: 80, // Zoom frame distance from top in pixels
            zoomLeft: 560 // Zoom frame distance from left in pixels
        });
    });
</script>

    {% block script %}

    {% endblock %}
  </body>

</html>

<!--

-->

shop/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ product.name }} {% endblock %}

{% block stylesheet %}

{% endblock %}



{% block content %}
<div class="row">
    <div class="col-lg-6">
        <a href="#" id="demo-trigger" class="magnifiable zoomable" data-medium-url="{{ product.image.url }}" data-large-url="{{ product.image.url }}">
            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" style="width: 100%; height: 400px; margin-top: 25px; margin-bottom: 10px">
        </a>
    </div>
    <div class="col-lg-6" style="margin-top: 25px; margin-bottom: 10px">
        <h1>{{ product.name }}</h1>
    <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
    <p>${{ product.price }}</p>
    <form action="{% url 'cart:cart_add' product.id %}" method="POST">
      {{ cart_product_form }}
      {% csrf_token %}
        <button type="submit" class="btn btn-primary">Add to cart</button>
    </form>
    <h3>Descriptions</h3>
        <p>{{ product.description|safe }}</p>
    </div>
</div>


    <h3 class="well" style="background-color: #fb4f59">Related Product</h3>
    <div class="row">
    {% for r in related %}
        <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12" style="padding: 25px;">
            <div class="hovereffect">
                <img class="img-responsive" src="{% if r.image %}{{ r.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" alt="" style="height: 100%; width: 100%;">
                <div class="overlay">
                   <h2><a href="{{ r.get_absolute_url }}">{{ product.name }}</a></h2>
                   <a class="info" href="{{ r.get_absolute_url }}">View Detail</a>
                </div>
            </div>
            <p>Price:  ৳ {{ product.price }}</p>
        </div>
    {% endfor %}
</div>



{% endblock %}




{% block script %}


{% endblock %}

shop/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

      <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist" style="margin-top: 10px;">
      <li {% if not category %}class="nav-item" {% endif %}>
        <a class="nav-link active" id="pills-home-tab" href="{% url 'shop:product_list' %}" role="tab" aria-controls="pills-home" aria-selected="true">All categories</a>
      </li>
      {% for c in categories %}
        <li {% if category.slug == c.slug %}class="nav-item"{% endif %}>
          <a class="nav-link" id="pills-profile-tab" href="{{ c.get_absolute_url }}" role="tab" aria-controls="pills-profile" aria-selected="false">{{ c.name }}</a>
        </li>
      {% endfor %}
    </ul>
<div class="row">
    {% for product in items %}
<div class="col-sm-3" style="padding: 25px; margin-top: 10px;" >
    <div class="hovereffect">
        <img class="img-responsive" src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" alt="" style="height: 100%; width: 100%;">
        <div class="overlay">
           <a class="info" href="{{ product.get_absolute_url }}">View Detail</a>
        </div>
    </div>
    <h6><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h6>
    <p>Price:  ৳ {{ product.price }}</p>
</div>
    {% endfor %}
</div>


<div class="row" style="padding: 10px; margin-top: 25px;">
    {% include 'pagination.html' %}
</div>
{% endblock %}


<!--
<div class="row">
        {% for product in items %}
<div class="col-lg-3" style="padding: 10px;">
<div class="card">
    <a href="{{ product.get_absolute_url }}">
        <img class="card-img-top" src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" alt="">
    </a>
    <div class="card-body">
      <h4 class="card-title">
        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
      </h4>
      <p>Price:  ৳ {{ product.price }}</p>
    </div>
    <div class="card-footer">
      <a href="{{ product.get_absolute_url }}"> <button class="btn btn-success btn-lg">View Details</button></a>
    </div>
  </div>
</div>
        {% endfor %}
    {% include 'pagination.html' %}
</div>

-->
<!--
 <div class="main">
                {% for product in items %}
                <div class="view view-tenth">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" style="height: 100%; width: 100%;"/>
                    <div class="mask">
                        <a href="{{ product.get_absolute_url }}"><h2>{{ product.name }}</h2></a>
                        <p>Price:  ৳ {{ product.price }}</p>
                        <a href="{{ product.get_absolute_url }}" class="info">View Details</a>
                    </div>
                </div>
                {% endfor %}
                    {% include 'pagination.html' %}
            </div>
-->

shop/templates/pagination.html
    {% if items.has_other_pages %}
        <div class="col-6 offset-3 text-center Pagination-set" style="margin-top: 30px;">
          <nav aria-label="">
            <ul class="pagination pagination-md">
            {% if items.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page={{ items.previous_page_number }}">Prev</a>
            </li>
            {% else %}
            <li class="page-item disabled">
              <a class="page-link"><span>Prev</span></a>
            </li>
            {% endif %}
            {% for i in page_range %}
              {% if items.number == i %}
              <li class="page-item active">
                <a class="page-link" href="#">{{i}}<span class="sr-only">(current)</span></a>
              </li>
              {% else %}
              <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
              {% endif %}
            {% endfor %}
            {% if items.has_next %}
            <li class="page-item"><a class="page-link" aria-label="Next" href="?page={{items.next_page_number}}">Next</a></li>
            {% else %}
            <li class="page-item disabled"><a class="page-link"><span>Next</span></a></li>
            {% endif %}
          </ul>
          </nav>
    {% endif %}

shop/templates/sample.html
{% extends 'base.html' %}
{% block title %} {% endblock %}

{% block stylesheet %}

{% endblock %}



{% block content %}

{% endblock %}

{% block script %}

{% endblock %}

shop/templates/slide.html
{% load static %}
<style>
  /* Make the image fully responsive */
  .carousel-inner img {
      width: 100%;
      height: 100%;
  }
  </style>

<div id="demo" class="carousel slide" data-ride="carousel" style="margin-top: 90px; margin-bottom: 30px;">

  <!-- Indicators -->
  <ul class="carousel-indicators">
    <li data-target="#demo" data-slide-to="0" class="active"></li>
    <li data-target="#demo" data-slide-to="1"></li>
    <li data-target="#demo" data-slide-to="2"></li>
  </ul>

  <!-- The slideshow -->
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'img/banner01.jpeg' %}" alt="Los Angeles" >
        <div class="carousel-caption">
            <h2>First Slide</h2>
            <button type="button" class="btn btn-warning">shop Now</button>
        </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'img/banner02.jpeg' %}" alt="Chicago">
        <div class="carousel-caption">
            <h2>First Slide</h2>
            <button type="button" class="btn btn-warning">shop Now</button>
        </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'img/banner03.jpeg' %}" alt="New York">
        <div class="carousel-caption">
            <h2>First Slide</h2>
            <button type="button" class="btn btn-warning">shop Now</button>
        </div>
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="carousel-control-prev" href="#demo" data-slide="prev">
    <span class="carousel-control-prev-icon"></span>
  </a>
  <a class="carousel-control-next" href="#demo" data-slide="next">
    <span class="carousel-control-next-icon"></span>
  </a>
</div>